server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:/ssl/deepdistillation.online.pfx
    key-store-password: 11uxoad5
    key-store-type: PKCS12

spring:
  application:
    name: navigation-backend-service
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.235:3306/voyage_planner_db_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

files:
  network-path: https://deepdistillation.online:${server.port}
  access-path: /static/**
  upload-path: /upload
  types:
  - image/png
  - image/jpeg
  - application/pdf
