server:
  port: 8081
  ssl:
    enabled: true
    key-store: file:D:/project/Voyage-Planner/service-all/navigation-backend-service/src/main/resources/ssl/www.deepdistillation.xyz.pfx
    key-store-password: uj2plp72
    key-store-type: PKCS12

spring:
  application:
    name: navigation-backend-service
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.235:3306/voyage_planner_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: never
      data-locations: classpath:data.sql