### 登录测试
POST https://localhost:8081/api/auth/login
Content-Type: application/json
{
  "username": "admin",
  "password": "123456"
}

### 成长路线测试
GET https://localhost:8081/api/roadmap/2
//Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIxIiwiaWF0IjoxNzgxNzg5MTU0LCJleHAiOjE3ODIzOTM5NTR9.TD_ELPNi03t0on0e8SosmxHTs-0PUJgEilihdlK7Sbk


### 注册测试
POST https://localhost:8081/api/auth/register
Content-Type: application/json
{
  "username": "zhangsan",
  "password": "123456",
  "name": "张三"
}


####文件上传测试
POST https://localhost:8081/api/files/upload
Content-Type: multipart/form-data
file: [选择图片文件]


###用户选择当前职位和目标职位
PUT https://localhost:8081/api/auth/1/rank
Content-Type: application/json
{
  "currentRank": "SECOND_OFFICER",
  "targetRank": "CAPTAIN"
}

###用户添加证书
POST https://localhost:8081/api/certificates
Content-Type: application/json

{
"userId": 1,
"typeId": 2,
"image": "https://example.com/certs/third.jpg",
"startDate": "2024-06-21"
}
